services:
  - type: web
    name: nm-auctions-v5
    env: node
    plan: starter
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: "10000"
